### ISSUE TITLE
Firebase Read-only file system

### ISSUE THREAD

**Issue by OllieStudio** [sendpulse/sendpulse-rest-api-node.js#17]
I´m trying to integrate SendPulse API Node.js wrapper with Firebase and got an error related
to saving the token the local File System. Is there a way to make it optional?

Error: EROFS: read-only file system, open 'null80832d857bb337b7bac4cb26e4186ca7'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1356:33)
    at saveToken (/user_code/node_modules/sendpulse-api/api/sendpulse.js:158:12)
    at IncomingMessage.<anonymous> (/user_code/node_modules/sendpulse-api/api/sendpulse.js:131:21)

**Comment by OllieStudio** [comment]
Got it working pointing the TOKEN_STORAGE var to a Firebase Storage url.

**Comment by sendpulse** [comment]
There's no way to make it optional. Token that you get from our system is correct for 1 hour. We have limit for getting token in a short period of time, so if you try to receive token with each request - your script will not work.

**Comment by OllieStudio** [comment]
Hi! There´s no problem with storing the token for 1 hour, but I should be able to implement my own way of storing it in the callback if the storage parameter is not set, something like:

`if (TOKEN_STORAGE) {
if (!fs.existsSync(TOKEN_STORAGE)) {
        mkdirSyncRecursive(TOKEN_STORAGE);
    }
}...`

**Comment by matthewjumpsoffbuildings** [comment]
soooo... we cant use this api with firebase functions?

**Comment by Stas-Buzunko** [comment]
1) I've been using this lib with firebase cloud functions for more than a year without a problem. 
2) Firebase DOES have tmp directory https://stackoverflow.com/a/54911222/5766054

this issue can be closed
