### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by victor-wayward** [sendpulse/sendpulse-rest-api-node.js#5]
When no connection is available, application crashes with:

Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:191:7)
    at _handle.close (net.js:509:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)

The error is not catch-able ... Is it returned somewhere?

**Comment by sendpulse** [comment]
Thank you for the feedback. We will add error catcher ASAP, it will return object:

`{ is_error: 1, message: ERROR_MESSAGE }`
